// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL0WnGq1CoKgdxNj8604ug8tS_7VKrn9U',
    appId: '1:182537378574:web:03d3be8a306bd0821c155f',
    messagingSenderId: '182537378574',
    projectId: 'application-f84cc',
    authDomain: 'application-f84cc.firebaseapp.com',
    storageBucket: 'application-f84cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvnrz8C91ABm42VY2hiAm4DtuIiyYsMP8',
    appId: '1:182537378574:android:e4310681ba539b4b1c155f',
    messagingSenderId: '182537378574',
    projectId: 'application-f84cc',
    storageBucket: 'application-f84cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKumvwf-qa2ii96np-O8YfKKm0Xdta0Q0',
    appId: '1:182537378574:ios:35b7443aa1449ebe1c155f',
    messagingSenderId: '182537378574',
    projectId: 'application-f84cc',
    storageBucket: 'application-f84cc.appspot.com',
    iosBundleId: 'com.example.myappf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKumvwf-qa2ii96np-O8YfKKm0Xdta0Q0',
    appId: '1:182537378574:ios:35b7443aa1449ebe1c155f',
    messagingSenderId: '182537378574',
    projectId: 'application-f84cc',
    storageBucket: 'application-f84cc.appspot.com',
    iosBundleId: 'com.example.myappf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL0WnGq1CoKgdxNj8604ug8tS_7VKrn9U',
    appId: '1:182537378574:web:ee748afafd8da1591c155f',
    messagingSenderId: '182537378574',
    projectId: 'application-f84cc',
    authDomain: 'application-f84cc.firebaseapp.com',
    storageBucket: 'application-f84cc.appspot.com',
  );
}
